### ISSUE TITLE
Doesn't work with Dalli

### ISSUE THREAD

**Issue by peterkeen** [mezis/level2#6]
We're using Dalli as our Memcached interface. When I try to configure level2 like this:

```
config.cache_store = :level2, {
  L1: [ :memory_store, size: 128.megabytes ],
  L2: [ :dalli_store ],
}
```

I get errors like this:

```
irb(main):006:0> Rails.cache.fetch(['whatever4']) { 'ghi' }
NoMethodError: undefined method `set' for nil:NilClass
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:303:in `write_entry'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/level2-0.3.0/lib/active_support/cache/level2.rb:62:in `block in write_entry'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/level2-0.3.0/lib/active_support/cache/level2.rb:61:in `each'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/level2-0.3.0/lib/active_support/cache/level2.rb:61:in `write_entry'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:391:in `block in write'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/level2-0.3.0/lib/active_support/cache/level2.rb:48:in `block in instrument'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:547:in `block in instrument'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:547:in `instrument'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/level2-0.3.0/lib/active_support/cache/level2.rb:47:in `instrument'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:389:in `write'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:588:in `save_block_result_to_cache'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:299:in `fetch'
	from (irb):6
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

From what I can tell, this is because Dalli [merges its connection handle into the options hash](https://github.com/petergoldstein/dalli/blob/v2.7.8/lib/active_support/cache/dalli_store.rb#L142-L148) for `read_entry` and `write_entry`. This is, of course, somewhat problematic for level2 because we try to call `read_entry` and `write_entry` directly. Would it be better to call `read` and `write` on the cache stores instead of `read_entry` and `write_entry`?

**Comment by mezis** [comment]
Thanks for the report @peterkeen!

From what I recall, calling `read` and `write` directly wasn't an option — although I can't remember off the top of my head exactly why. It could have been because of a bad interaction with `ActiveSupport::Notifications`, or it could have been because at the time I was trying to preserve compatibility with Rails 3 (which I'd like to drop anyhow).

I'll have a look, but if you feel like trying a fix, do tell. Pull requests are always welcome :)

**Comment by peterkeen** [comment]
Circling back after quite some time, it appears that Rails' built-in `ActiveSupport::Cache::MemCacheStore` (built on dalli) works great with this gem. Gonna close and try to see if level2 makes sense for my current gig.
