### ISSUE TITLE
Incompatibility with Ruby 3 / Rails 6.1

### ISSUE THREAD

**Issue by futuretap** [mezis/level2#9]
When calling `Rails.cache.exist?(key)` level2 throws an exception:

```
#<ArgumentError: wrong number of arguments (given 2, expected 1)>

/bundler/gems/level2/lib/active_support/cache/level2.rb:97:in `record_event'`,
/bundler/gems/level2/lib/active_support/cache/level2.rb:73:in `block in read_entry_from',
/bundler/gems/level2/lib/active_support/cache/level2.rb:85:in `each',
/bundler/gems/level2/lib/active_support/cache/level2.rb:85:in `each',
/bundler/gems/level2/lib/active_support/cache/level2.rb:85:in `each',
/bundler/gems/level2/lib/active_support/cache/level2.rb:85:in `each',
/bundler/gems/level2/lib/active_support/cache/level2.rb:85:in `detect',
/bundler/gems/level2/lib/active_support/cache/level2.rb:85:in `read_entry_from',
/bundler/gems/level2/lib/active_support/cache/level2.rb:40:in `read_entry',
/gems/activesupport-6.1.7/lib/active_support/cache.rb:510:in `block in exist?'",
/gems/activesupport-6.1.7/lib/active_support/cache.rb:726:in `block in instrument'",
/gems/activesupport-6.1.7/lib/active_support/notifications.rb:205:in `instrument'",
/gems/activesupport-6.1.7/lib/active_support/cache.rb:726:in `instrument'",
/gems/activesupport-6.1.7/lib/active_support/cache.rb:509:in `exist?'",
```

**Comment by futuretap** [comment]
Here's a fix, feel free to pull:
https://github.com/futuretap/level2/commit/46cacb48ddc9402beff3a0b0dbd0059a4b7bc774
